modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="saintsdragons"
version="1.0.0"
displayName="Saint's Dragons"
description='''
Adds animated, AI-driven dragons or wyverns or whatever the heck you wanna call them flying reptiles to Minecraft.
'''
authors="Leon Saint"
mixins=["saintsdragons.mixins.json"]

[[dependencies.saintsdragons]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.saintsdragons]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.saintsdragons]]
modId="geckolib"
mandatory=true
versionRange="[4.7.4,)"
ordering="BEFORE"
side="BOTH"
